version: "3.8"

services:
  mysqldb:
    image: mysql
    command: mysqld --sql_mode="" --max_connections=1100 --general-log=1 --general-log-file=/tmp/mysql-general-log.log
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=lucreziasPresent
      - TEST_USERS_PASSWORD=${TEST_USERS_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./feed.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: 'cat /tmp/mysql-general-log.log | grep "Tcp port: 3306  Unix socket: /var/run/mysqld/mysqld.sock"'
      interval: 10s
      retries: 120

  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./lucreziasPresent-backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "web.cors.allowed-origins"   : "http://localhost:3000",
        "spring.datasource.url"      : "jdbc:mysql://mysqldb:3306/lucreziasPresent?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "rootPass",
        "spring.profiles.active"     : "default"
      }'
    stdin_open: true
    tty: true

  frontend:
    depends_on:
      mysqldb:
        condition: service_healthy
      backend:
        condition: service_started
    build:
      context: ./lucreziasPresent-frontend
    ports:
      - "3000:3000"

volumes:
  db: