version: "3.8"

services:
  mysqldb-func:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=lucreziasPresent
      - TEST_USERS_PASSWORD=${TEST_USERS_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./feed-functional.sh:/docker-entrypoint-initdb.d/init.sh

  backend:
    depends_on:
      - mysqldb-func
    build:
      context: ./lucreziasPresent-backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "web.cors.allowed-origins"   : "http://localhost:3000",
        "spring.datasource.url"      : "jdbc:mysql://mysqldb-func:3306/lucreziasPresent?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "rootPass",
        "spring.profiles.active"     : "default"
      }'
    stdin_open: true
    tty: true

  frontend:
    depends_on:
      - mysqldb-func
      - backend
    build:
      context: ./lucreziasPresent-frontend
    ports:
      - "3000:3000"
