version: '3.3'
services:
  lucrezia:
    container_name: lucrezia
    network_mode: bridge
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8080:8080'
    image: registry.digitalocean.com/digital-ocean-registry-alfonso/lucrezia:latest
    restart: always
    env_file: ./env_vars.txt