app:
  default-password: ${env.DEFAULT_PASSWORD}
web:
  cors:
    allowed-origins: ${env.ALLOWED_ORIGINS}
    allowed-methods: "GET, POST, PATCH, DELETE, OPTIONS"
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${env.DB_URL}
    username: ${env.MYSQL_USERNAME}
    password: ${env.MYSQL_PASSWORD}
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  compression:
    enabled: "true"
