web:
  cors:
    allowed-origins: "http://localhost:3000/"
    allowed-methods: "GET, POST"
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucreziasPresent
    username: admin
    password: password
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  compression:
    enabled: "true"
