version: '3.3'
services:
  lucrezia:
    network_mode: bridge
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8080:8080'
    image: alfonsoristorato/lucrezia
    restart: always